DROP TABLE IF EXISTS payments;
DROP TABLE IF EXISTS bookings;
DROP TABLE IF EXISTS tours;
DROP TABLE IF EXISTS hotels;
DROP TABLE IF EXISTS destinations;
DROP TABLE IF EXISTS clients;

CREATE TABLE clients (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name varchar(200) NOT NULL,
    phone varchar(30) NOT NULL,
    email varchar(200),
    passport_number varchar(30),
    created_at timestamp without time zone NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX ux_clients_phone ON clients (phone);

CREATE TABLE destinations (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    country varchar(120) NOT NULL,
    city varchar(120) NOT NULL,
    name varchar(200) NOT NULL,
    description text NOT NULL DEFAULT ''
);

CREATE INDEX ix_destinations_search ON destinations (country, city, name);

CREATE TABLE hotels (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    destination_id integer NOT NULL REFERENCES destinations (id) ON DELETE RESTRICT,
    name varchar(200) NOT NULL,
    stars integer NOT NULL CHECK (stars BETWEEN 1 AND 5),
    address varchar(300) NOT NULL DEFAULT '',
    description text NOT NULL DEFAULT ''
);

CREATE INDEX ix_hotels_destination_id ON hotels (destination_id);

CREATE TABLE tours (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    destination_id integer NOT NULL REFERENCES destinations (id) ON DELETE RESTRICT,
    hotel_id integer NOT NULL REFERENCES hotels (id) ON DELETE RESTRICT,
    title varchar(220) NOT NULL,
    description text NOT NULL DEFAULT '',
    price_per_person numeric(12, 2) NOT NULL CHECK (price_per_person >= 0),
    start_date date NOT NULL,
    end_date date NOT NULL,
    available_spots integer NOT NULL CHECK (available_spots >= 0),
    meal_type varchar(80) NOT NULL DEFAULT 'Без питания',
    transport_type varchar(80) NOT NULL DEFAULT 'Авиа',
    CONSTRAINT tours_dates_check CHECK (end_date >= start_date)
);

CREATE INDEX ix_tours_destination_id ON tours (destination_id);
CREATE INDEX ix_tours_hotel_id ON tours (hotel_id);
CREATE INDEX ix_tours_start_date ON tours (start_date);
CREATE INDEX ix_tours_price ON tours (price_per_person);

CREATE TABLE bookings (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tour_id integer NOT NULL REFERENCES tours (id) ON DELETE RESTRICT,
    client_id integer NOT NULL REFERENCES clients (id) ON DELETE RESTRICT,
    people_count integer NOT NULL CHECK (people_count > 0),
    total_price numeric(12, 2) NOT NULL CHECK (total_price >= 0),
    status varchar(30) NOT NULL DEFAULT 'new',
    booked_at timestamp without time zone NOT NULL DEFAULT now(),
    notes text,
    CONSTRAINT bookings_status_check CHECK (status IN ('new', 'confirmed', 'paid', 'cancelled'))
);

CREATE INDEX ix_bookings_tour_id ON bookings (tour_id);
CREATE INDEX ix_bookings_client_id ON bookings (client_id);
CREATE INDEX ix_bookings_status ON bookings (status);

CREATE TABLE payments (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id integer NOT NULL REFERENCES bookings (id) ON DELETE CASCADE,
    paid_at timestamp without time zone NOT NULL DEFAULT now(),
    amount numeric(12, 2) NOT NULL CHECK (amount > 0),
    method varchar(80) NOT NULL,
    comment text
);

CREATE INDEX ix_payments_booking_id ON payments (booking_id);
